// Code generated by sqlc. DO NOT EDIT.
// source: insert_log.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertLog = `-- name: InsertLog :one
insert into tb_search_log(http_request)
VALUES ($1) returning id
`

func (q *Queries) InsertLog(ctx context.Context, httpRequest sql.NullString) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertLog, httpRequest)
	var id int32
	err := row.Scan(&id)
	return id, err
}
