// Code generated by sqlc. DO NOT EDIT.
// source: insert_log.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertLog = `-- name: InsertLog :one
insert into tb_search_log(http_request, type, code, error)
VALUES ($1,$2,$3,$4) returning id
`

type InsertLogParams struct {
	HttpRequest sql.NullString
	Type        sql.NullString
	Code        sql.NullInt32
	Error       sql.NullString
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertLog,
		arg.HttpRequest,
		arg.Type,
		arg.Code,
		arg.Error,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
