// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
)

type TbSearchLog struct {
	ID          int32
	HttpRequest sql.NullString
	Type        sql.NullString
	Code        sql.NullInt32
	Timestamp   sql.NullTime
	Error       sql.NullString
}
